# Generated by Django 5.0.1 on 2024-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='pictures/', verbose_name='Painting')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/', verbose_name='Files')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('href', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Link')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Link to Leetcode')),
                ('easy_tasks_leetcode', models.IntegerField(blank=True, default=0, verbose_name='Easy solved Leetcode problems')),
                ('medium_tasks_leetcode', models.IntegerField(blank=True, default=0, verbose_name='Average solved Leetcode problems')),
                ('hard_tasks_leetcode', models.IntegerField(blank=True, default=0, verbose_name='Complex solved problems Leetcode')),
                ('type', models.CharField(choices=[('picture', 'Painting'), ('game', 'A game'), ('bot', 'Bot'), ('autotest', 'Autotest'), ('leetcode', 'Leetcode'), ('certificate', 'QA Certificates')], max_length=50)),
            ],
        ),
    ]
