# Generated by Django 5.0.1 on 2024-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='pictures/', verbose_name='Картина')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/', verbose_name='Файлы')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('href', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на Leetcode')),
                ('type', models.CharField(choices=[('picture', 'Картина'), ('game', 'Игра'), ('bot', 'Бот'), ('site', 'Сайт'), ('autotest', 'Автотест'), ('leetcode', 'Leetcode'), ('certificate', 'QA Сертификаты'), ('data_science', 'Data Science')], max_length=50)),
            ],
        ),
    ]
