# Generated by Django 5.0.1 on 2024-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='easy_tasks_leetcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Легких решённых задач Leetcode'),
        ),
        migrations.AddField(
            model_name='file',
            name='hard_tasks_leetcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сложных решённых задач Leetcode'),
        ),
        migrations.AddField(
            model_name='file',
            name='medium_tasks_leetcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Средних решённых задач Leetcode'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('picture', 'Картина'), ('game', 'Игра'), ('bot', 'Бот'), ('site', 'Сайт'), ('autotest', 'Автотест'), ('leetcode', 'Leetcode'), ('certificate', 'QA Сертификаты')], max_length=50),
        ),
    ]
